from typing import Protocol
from uuid import UUID

from src.application.billing.dto import (
    CreatedPayment,
    NewPaymentData,
    NewTariffData,
    PaymentInfo,
    TariffInfo,
    UpdateTariffData,
)


class TariffRepository(Protocol):
    async def list_active(self) -> tuple[TariffInfo, ...]: ...
    async def list_all(self) -> tuple[TariffInfo, ...]: ...
    async def get_by_id(self, tariff_id: UUID) -> TariffInfo | None: ...
    async def create(self, data: NewTariffData) -> TariffInfo: ...
    async def update(self, tariff_id: UUID, data: UpdateTariffData) -> TariffInfo | None: ...
    async def delete(self, tariff_id: UUID) -> bool: ...


class PaymentRepository(Protocol):
    async def create(self, data: NewPaymentData) -> PaymentInfo: ...
    async def get_by_id(self, payment_id: UUID) -> PaymentInfo | None: ...
    async def get_by_external_id(self, external_id: str) -> PaymentInfo | None: ...
    async def list_pending_yookassa(self) -> tuple[PaymentInfo, ...]: ...
    async def list_recent(self, limit: int) -> tuple[PaymentInfo, ...]: ...
    async def list_by_user_id(self, user_id: UUID, limit: int) -> tuple[PaymentInfo, ...]: ...
    async def set_status(
        self,
        payment_id: UUID,
        status: str,
        *,
        completed_at: object = None,
    ) -> None: ...


class BillingUnitOfWork(Protocol):
    tariffs: TariffRepository
    payments: PaymentRepository

    async def __aenter__(self) -> "BillingUnitOfWork": ...
    async def __aexit__(self, exc_type: object, exc: object, tb: object) -> None: ...
    async def commit(self) -> None: ...
    async def rollback(self) -> None: ...


class YooKassaGateway(Protocol):
    async def create_payment(
        self,
        amount_rub: int,
        description: str,
        *,
        metadata: dict[str, str],
    ) -> CreatedPayment: ...

    async def get_payment_status(self, external_id: str) -> str: ...
    # Returns: 'pending' | 'completed' | 'failed' | 'cancelled'
