"""Admin screen composition."""

from .broadcasts import (
    build_admin_broadcast_launched_text,
    build_admin_broadcast_preview_text,
    build_admin_broadcast_segment_text,
    build_admin_broadcast_text_prompt,
    build_admin_broadcasts_text,
    format_segment_label,
)
from .bulk import (
    build_admin_users_bulk_actions_text,
    build_admin_users_bulk_cancelled_text,
    build_admin_users_bulk_delete_confirm_text,
    build_admin_users_bulk_disable_confirm_text,
    build_admin_users_bulk_failed_text,
    build_admin_users_bulk_history_text,
    build_admin_users_bulk_issue_confirm_text,
    build_admin_users_bulk_progress_text,
    build_admin_users_bulk_queued_text,
    build_admin_users_bulk_result_text,
    build_admin_users_global_bulk_actions_text,
    build_admin_users_global_bulk_delete_confirm_text,
    build_admin_users_global_bulk_disable_confirm_text,
    build_admin_users_global_bulk_issue_confirm_text,
)
from .home import (
    ADMIN_ACTION_FEEDBACK,
    ADMIN_SECTION_SCREENS,
    build_access_mode_text,
    build_admin_home_text,
    build_max_vpn_accesses_prompt_text,
    format_access_mode,
    format_max_vpn_accesses_per_user,
)
from .promos import (
    build_admin_promo_create_bonus_text,
    build_admin_promo_create_code_text,
    build_admin_promo_create_limit_text,
    build_admin_promo_create_scope_text,
    build_admin_promo_create_title_text,
    build_admin_promo_create_type_text,
    build_admin_promo_detail_text,
    build_admin_promos_list_text,
)
from .support import (
    build_admin_support_reply_prompt_text,
    build_admin_support_ticket_detail_text,
    build_admin_support_tickets_text,
)
from .users import (
    build_admin_user_access_text,
    build_admin_user_detail_text,
    build_admin_user_history_text,
    build_admin_users_search_prompt_text,
    build_admin_users_search_result_text,
    build_admin_users_text,
)

__all__ = [
    "ADMIN_ACTION_FEEDBACK",
    "ADMIN_SECTION_SCREENS",
    "build_access_mode_text",
    "build_admin_broadcast_launched_text",
    "build_admin_broadcast_preview_text",
    "build_admin_broadcast_segment_text",
    "build_admin_broadcast_text_prompt",
    "build_admin_broadcasts_text",
    "build_admin_home_text",
    "build_admin_promo_create_bonus_text",
    "build_admin_promo_create_code_text",
    "build_admin_promo_create_limit_text",
    "build_admin_promo_create_scope_text",
    "build_admin_promo_create_title_text",
    "build_admin_promo_create_type_text",
    "build_admin_promo_detail_text",
    "build_admin_promos_list_text",
    "build_admin_support_reply_prompt_text",
    "build_admin_support_ticket_detail_text",
    "build_admin_support_tickets_text",
    "build_admin_user_access_text",
    "build_admin_user_detail_text",
    "build_admin_user_history_text",
    "build_admin_users_bulk_actions_text",
    "build_admin_users_bulk_cancelled_text",
    "build_admin_users_bulk_delete_confirm_text",
    "build_admin_users_bulk_disable_confirm_text",
    "build_admin_users_bulk_failed_text",
    "build_admin_users_bulk_history_text",
    "build_admin_users_bulk_issue_confirm_text",
    "build_admin_users_bulk_progress_text",
    "build_admin_users_bulk_queued_text",
    "build_admin_users_bulk_result_text",
    "build_admin_users_global_bulk_actions_text",
    "build_admin_users_global_bulk_delete_confirm_text",
    "build_admin_users_global_bulk_disable_confirm_text",
    "build_admin_users_global_bulk_issue_confirm_text",
    "build_admin_users_search_prompt_text",
    "build_admin_users_search_result_text",
    "build_admin_users_text",
    "build_max_vpn_accesses_prompt_text",
    "format_access_mode",
    "format_max_vpn_accesses_per_user",
    "format_segment_label",
]
