"""reviews: unique user_id constraint

Revision ID: bc2556ac9285
Revises: 20260412_000005
Create Date: 2026-04-12 20:47:07.356427

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = 'bc2556ac9285'
down_revision: str | None = '20260412_000005'
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # Удаляем дубликаты отзывов, оставляя самый последний по user_id
    op.execute("""
        DELETE FROM reviews
        WHERE id NOT IN (
            SELECT DISTINCT ON (user_id) id
            FROM reviews
            ORDER BY user_id, created_at DESC, id
        )
    """)

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('promo_codes_code_key'), 'promo_codes', type_='unique')
    op.drop_constraint(op.f('uq_promo_redemptions_promo_user'), 'promo_redemptions', type_='unique')
    op.create_unique_constraint('uq_reviews_user_id', 'reviews', ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_reviews_user_id', 'reviews', type_='unique')
    op.create_unique_constraint(op.f('uq_promo_redemptions_promo_user'), 'promo_redemptions', ['promo_code_id', 'user_id'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('promo_codes_code_key'), 'promo_codes', ['code'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
